#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64GB
#SBATCH --time=3:00:00
#SBATCH --account=jessetho_1016  


SCRIPTS_DIR=scripts
ENV_NAME=vl

module purge && echo "purged modules" &&\
source $PWD/$SCRIPTS_DIR/init_env_on_carc.sh &&\
conda activate $ENV_NAME &&\
echo "done setup env" &&\
sh $SCRIPTS_DIR/download_data_wikipedia.sh &&\\
echo "done downloading wikipedia dataset"



