#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16GB
#SBATCH --time=3:00:00
#SBATCH --account=jessetho_1016  
#SBATCH --gres=gpu:v100:1 
#SBATCH --partition=gpu

SCRIPTS_DIR=scripts
ENV_NAME=vl

module purge && echo "purged modules" &&\
source $PWD/$SCRIPTS_DIR/init_env_on_carc_with_gpu.sh &&\
conda activate $ENV_NAME &&\
echo "done init and activating env: $ENV_NAME"

#sh GLUE/data/runs/clipbert-avg-visual-features/run.sh &&\
#echo "done clipbert-avg-visual-features"

#sh GLUE/data/runs/lxmert-zeroed-visual-features/run.sh &&\
#echo "done lxmert-zeroed-visual-features"

#sh GLUE/data/runs/clipbert-no-visual-features/run.sh &&\
#echo "done clipbert-no-visual-features"

#sh GLUE/data/runs/flava-no-visual-features/run.sh &&\
#echo "done flava-no-visual-features"

#sh GLUE/data/runs/clipbert-zeroed-visual-features/run.sh &&\
#echo "done clipbert-zeroed-visual-features"

#sh GLUE/data/runs/bert-base-trained-lxmert/run.sh &&\
#echo "done bert-base-trained-lxmert"

#sh GLUE/data/runs/clipbert-zero-image-visual-features/run.sh &&\
#echo "done clipbert-zero-image-visual-features"

#sh GLUE/data/runs/lxmert-no-visual-features/run.sh &&\
#echo "done lxmert-no-visual-features"

#sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
#echo "done visualbert-zeroed-visual-features"

#sh GLUE/data/runs/clipbert-imagined-visual-features/run.sh &&\
#echo "done clipbert-imagined-visual-features"

#sh GLUE/data/runs/bert-base-trained-wikipedia/run.sh &&\
#echo "done bert-base-trained-wikipedia"

#sh GLUE/data/runs/bert-base-trained-lxmert-scratch/run.sh &&\
#echo "done bert-base-trained-lxmert-scratch"

#sh GLUE/data/runs/bert-base/run.sh &&\
#echo "done bert-base"

sh GLUE/data/runs/lxmert-zero-image-visual-features/run.sh &&\
echo "done lxmert-zero-image-visual-features"

sh GLUE/data/runs/visualbert-zero-image-visual-features/run.sh &&\
echo "done visualbert-zero-image-visual-features"

sh GLUE/data/runs/lxmert-avg-visual-features/run.sh &&\
echo "done lxmert-avg-visual-features"

sh GLUE/data/runs/visualbert-no-visual-features/run.sh &&\
echo "done visualbert-no-visual-features"

sh GLUE/data/runs/visualbert-avg-visual-features/run.sh &&\
echo "done visualbert-avg-visual-features"

echo "done with all scripts"



