#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16GB
#SBATCH --time=24:00:00
#SBATCH --account=jessetho_1016
#SBATCH --gres=gpu:v100:1
#SBATCH --partition=gpu

SCRIPTS_DIR=scripts
ENV_NAME=vl

module purge && echo "purged modules" &&\
source $PWD/$SCRIPTS_DIR/init_env_on_carc_with_gpu.sh &&\
conda activate $ENV_NAME &&\
echo "done init and activating env: $ENV_NAME"

NUM_DONE=0



echo "evaluating lxmert-zero-image-visual-features on 3:qnli"
TASK_ID=3
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/lxmert-zero-image-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/1 : lxmert-zero-image-visual-features"&&\
rm -r GLUE/data/logs/lxmert-zero-image-visual-features/*/checkpoint* &&\
echo "erased ckpts"



echo "evaluating lxmert-zeroed-visual-features on 3:qnli"
TASK_ID=3
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/lxmert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/2 : lxmert-zeroed-visual-features"

echo "evaluating lxmert-zeroed-visual-features on 4:qqp"
TASK_ID=4
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/lxmert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/3 : lxmert-zeroed-visual-features"&&\
rm -r GLUE/data/logs/lxmert-zeroed-visual-features/*/checkpoint* &&\
echo "erased ckpts"



echo "evaluating visualbert-no-visual-features on 1:mnli"
TASK_ID=1
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/4 : visualbert-no-visual-features"

echo "evaluating visualbert-no-visual-features on 3:qnli"
TASK_ID=3
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/5 : visualbert-no-visual-features"

echo "evaluating visualbert-no-visual-features on 4:qqp"
TASK_ID=4
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/6 : visualbert-no-visual-features"&&\
rm -r GLUE/data/logs/visualbert-no-visual-features/*/checkpoint* &&\
echo "erased ckpts"



echo "evaluating visualbert-no-visual-features-finetuned-lxmert on 4:qqp"
TASK_ID=4
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-lxmert/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/7 : visualbert-no-visual-features-finetuned-lxmert"

echo "evaluating visualbert-no-visual-features-finetuned-lxmert on 5:rte"
TASK_ID=5
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-lxmert/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/8 : visualbert-no-visual-features-finetuned-lxmert"

echo "evaluating visualbert-no-visual-features-finetuned-lxmert on 6:sst2"
TASK_ID=6
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-lxmert/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/9 : visualbert-no-visual-features-finetuned-lxmert"

echo "evaluating visualbert-no-visual-features-finetuned-lxmert on 7:stsb"
TASK_ID=7
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-lxmert/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/10 : visualbert-no-visual-features-finetuned-lxmert"&&\
rm -r GLUE/data/logs/visualbert-no-visual-features-finetuned-lxmert/*/checkpoint* &&\
echo "erased ckpts"



echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 1:mnli"
TASK_ID=1
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/11 : visualbert-no-visual-features-finetuned-wikipedia"

echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 2:mrpc"
TASK_ID=2
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/12 : visualbert-no-visual-features-finetuned-wikipedia"

echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 3:qnli"
TASK_ID=3
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/13 : visualbert-no-visual-features-finetuned-wikipedia"

echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 4:qqp"
TASK_ID=4
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/14 : visualbert-no-visual-features-finetuned-wikipedia"

echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 5:rte"
TASK_ID=5
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/15 : visualbert-no-visual-features-finetuned-wikipedia"

echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 6:sst2"
TASK_ID=6
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/16 : visualbert-no-visual-features-finetuned-wikipedia"

echo "evaluating visualbert-no-visual-features-finetuned-wikipedia on 7:stsb"
TASK_ID=7
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-no-visual-features-finetuned-wikipedia/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/17 : visualbert-no-visual-features-finetuned-wikipedia"&&\
rm -r GLUE/data/logs/visualbert-no-visual-features-finetuned-wikipedia/*/checkpoint* &&\
echo "erased ckpts"



echo "evaluating visualbert-zero-image-visual-features on 1:mnli"
TASK_ID=1
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zero-image-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/18 : visualbert-zero-image-visual-features"

echo "evaluating visualbert-zero-image-visual-features on 3:qnli"
TASK_ID=3
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zero-image-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/19 : visualbert-zero-image-visual-features"

echo "evaluating visualbert-zero-image-visual-features on 4:qqp"
TASK_ID=4
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zero-image-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/20 : visualbert-zero-image-visual-features"

echo "evaluating visualbert-zero-image-visual-features on 6:sst2"
TASK_ID=6
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zero-image-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/21 : visualbert-zero-image-visual-features"

echo "evaluating visualbert-zero-image-visual-features on 7:stsb"
TASK_ID=7
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zero-image-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/22 : visualbert-zero-image-visual-features"&&\
rm -r GLUE/data/logs/visualbert-zero-image-visual-features/*/checkpoint* &&\
echo "erased ckpts"



echo "evaluating visualbert-zeroed-visual-features on 1:mnli"
TASK_ID=1
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/23 : visualbert-zeroed-visual-features"

echo "evaluating visualbert-zeroed-visual-features on 3:qnli"
TASK_ID=3
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/24 : visualbert-zeroed-visual-features"

echo "evaluating visualbert-zeroed-visual-features on 4:qqp"
TASK_ID=4
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/25 : visualbert-zeroed-visual-features"

echo "evaluating visualbert-zeroed-visual-features on 5:rte"
TASK_ID=5
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/26 : visualbert-zeroed-visual-features"

echo "evaluating visualbert-zeroed-visual-features on 6:sst2"
TASK_ID=6
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/27 : visualbert-zeroed-visual-features"

echo "evaluating visualbert-zeroed-visual-features on 7:stsb"
TASK_ID=7
export TASK_ID
source activate $ENV_NAME &&\
sh GLUE/data/runs/visualbert-zeroed-visual-features/run.sh &&\
NUM_DONE=$((NUM_DONE+1)) &&\
echo "done script $NUM_DONE/28 : visualbert-zeroed-visual-features"echo "done trying to run all 28 scripts"